# Generated by Django 5.1.4 on 2026-02-12 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=100, unique=True)),
                ('roomCapacity', models.IntegerField()),
                ('signageCapacity', models.IntegerField(default=0)),
                ('parkingCapacity', models.IntegerField(default=0)),
                ('buildingAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('contactPerson', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitID', models.IntegerField()),
                ('rentAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vatAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('signageFees', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parkingFees', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contractLength', models.PositiveSmallIntegerField(choices=[(6, '6 months'), (12, '12 months')])),
                ('contractStart', models.DateField()),
                ('contractEnd', models.DateField(blank=True, null=True)),
                ('pastLease', models.BooleanField(blank=True, default=True, null=True)),
                ('buildingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.building')),
                ('tenantName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIssued', models.DateField()),
                ('dateDue', models.DateField(blank=True, null=True)),
                ('billingFor', models.CharField(choices=[('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('WATER', 'Water')], max_length=20)),
                ('amountDue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penaltyFee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.tenant')),
            ],
        ),
    ]
