# Generated by Django 5.1.4 on 2026-02-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='parkingFees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='signageFees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
