# Generated by Django 6.0.1 on 2026-02-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=100)),
                ('roomCapacity', models.IntegerField()),
                ('signageCapacity', models.IntegerField(default=0)),
                ('parkingCapacity', models.IntegerField(default=0)),
                ('buildingAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
