# Generated by Django 5.1.4 on 2026-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0002_alter_lease_parkingfees_alter_lease_signagefees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='pastLease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('pastLease', False)), fields=('tenantName',), name='unique_active_lease_per_tenant'),
        ),
    ]
