# Generated by Django 6.0.1 on 2026-02-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0002_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='buildingName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billingApp.building'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
