# Generated by Django 5.1.4 on 2026-02-03 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0003_tenant_buildingname_alter_building_buildingname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantID', models.CharField(max_length=100)),
                ('unitID', models.IntegerField()),
                ('rentAmount', models.FloatField()),
                ('vatAmount', models.FloatField()),
                ('buildingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.building')),
                ('tenantName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.tenant')),
            ],
        ),
    ]
