# Generated by Django 5.1.4 on 2026-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0004_alter_building_id_alter_tenant_id_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenantID',
        ),
        migrations.AddField(
            model_name='lease',
            name='contractEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='contractStart',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='pastLease',
            field=models.BooleanField(default=True),
        ),
    ]
