# Generated by Django 5.1.4 on 2026-03-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingApp", "0005_add_admin_fk_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="modified_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="billingApp.account"),
        ),
        migrations.AddField(
            model_name="building",
            name="modified_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="billingApp.account"),
        ),
        migrations.AddField(
            model_name="lease",
            name="modified_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="billingApp.account"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="modified_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="billingApp.account"),
        ),
    ]
