# Generated by Django 5.1.4 on 2026-02-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0005_remove_lease_tenantid_lease_contractend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='contractLength',
            field=models.PositiveSmallIntegerField(choices=[(6, '6 months'), (12, '12 months')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lease',
            name='contractEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lease',
            name='contractStart',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lease',
            name='vatAmount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
