# Generated by Django 5.1.4 on 2026-03-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0006_add_modified_by_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
