# Generated by Django 5.1.4 on 2026-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0006_lease_contractlength_alter_lease_contractend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='pastLease',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
