# Generated by Django 5.1.4 on 2026-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0007_alter_lease_pastlease'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='parkingFees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='signageFees',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
