# Generated by Django 5.1.4 on 2026-03-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0007_alter_tenant_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrecord',
            name='admin_ID',
        ),
        migrations.RemoveField(
            model_name='building',
            name='admin_ID',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='admin_ID',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='admin_ID',
        ),
    ]
