# Generated by Django 5.1.4 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingApp", "0008_remove_billingrecord_admin_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
    ]
