# Generated by Django 5.1.4 on 2026-03-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0009_add_modified_at_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitID', models.IntegerField()),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.building')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billingApp.account')),
            ],
            options={
                'unique_together': {('building', 'unitID')},
            },
        ),
        migrations.AlterField(
            model_name='lease',
            name='unitID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.units'),
        ),
    ]
