# Generated by Django 5.1.4 on 2026-03-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0010_units_alter_lease_unitid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='roomCapacity',
        ),
    ]
