# Generated by Django 5.1.4 on 2026-03-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0011_remove_building_roomcapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('datePaid', models.DateField()),
                ('paymentType', models.CharField(max_length=20)),
                ('referenceNumber', models.CharField(max_length=50)),
                ('verificationStatus', models.CharField(max_length=20)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subAccountName', models.CharField(blank=True, max_length=50, null=True)),
                ('proofOfPayment', models.FileField(blank=True, null=True, upload_to='proof_of_payment/')),
                ('paymentMethod', models.CharField(blank=True, max_length=20, null=True)),
                ('billingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.billingrecord')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billingApp.account')),
                ('tenantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingApp.tenant')),
            ],
        ),
    ]
