# Generated by Django 5.1.4 on 2026-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0012_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paymentType',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('PDC', 'PDC')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verificationStatus',
            field=models.BooleanField(default=False),
        ),
    ]
