# Generated by Django 5.1.4 on 2026-04-08 07:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0013_remove_payment_paymenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='carryover_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingAddress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingName',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
