# Generated by Django 5.1.4 on 2026-04-19 09:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0014_tenant_carryover_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='electric_carryover',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='water_carryover',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('UNDERPAID', 'Underpaid'), ('OVERPAID', 'Overpaid')], default='UNPAID', max_length=10),
        ),
    ]
