# Generated by Django 5.1.4 on 2026-04-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0015_tenant_electric_carryover_tenant_water_carryover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='electric_carryover',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='water_carryover',
        ),
    ]
