# Generated by Django 5.1.4 on 2026-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0016_remove_tenant_electric_carryover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='leaseAttachment',
            field=models.FileField(blank=True, null=True, upload_to='lease_attachments/'),
        ),
    ]
