# Generated by Django 5.1.4 on 2026-05-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0017_lease_leaseattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
