# Generated by Django 5.1.4 on 2026-05-01 13:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0018_lease_archived_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='carryoverAdjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('UNDERPAID', 'Underpaid'), ('OVERPAID', 'Overpaid')], default='UNPAID', max_length=10),
        ),
    ]
