# Generated by Django 5.1.4 on 2026-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0019_billingrecord_carryoveradjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('UNDERPAID', 'Underpaid'), ('PAID', 'Paid'), ('OVERPAID', 'Overpaid')], default='UNPAID', max_length=10),
        ),
    ]
