# Generated by Django 5.1.4 on 2026-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0020_alter_billingrecord_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lease',
            name='unique_active_lease_per_tenant',
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('UNDERPAID', 'Underpaid'), ('PAID', 'Paid'), ('OVERPAID', 'Overpaid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=10),
        ),
    ]
