# Generated by Django 5.1.4 on 2026-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0021_remove_lease_unique_active_lease_per_tenant_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('pastLease', False)), fields=('tenantName',), name='unique_active_lease_per_tenant'),
        ),
    ]
