# Generated by Django 5.1.4 on 2026-05-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingApp', '0022_lease_unique_active_lease_per_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lease',
            name='unique_active_lease_per_tenant',
        ),
    ]
