from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_page, name='login_page'),
    path('home_page/', views.home_page, name='home_page'),
    path('buildings_main/', views.buildings_main, name='buildings_main'),
    path('tenants_main/', views.tenants_main, name='tenants_main'),
    path('add_building/', views.add_building, name='add_building'),
    path('building_details/<int:pk>/', views.building_details, name='building_details'),
    path('delete_building/<int:pk>/', views.delete_building, name='delete_building'),
    path('add_tenant/', views.add_tenant, name='add_tenant'),
    path('tenant_details/<int:pk>/', views.tenant_details, name='tenant_details'),
    path('delete_tenant/<int:pk>/', views.delete_tenant, name='delete_tenant'),
    path('add_lease/<int:pk>/', views.add_lease, name='add_lease'),
    path('delete_lease/<int:pk>/', views.delete_lease, name='delete_lease'),
    path('billing_records_main/', views.billing_records_main, name='billing_records_main'),
    path('view_bills/<int:pk>/', views.view_bills, name='view_bills'),
    path('add_bill/<int:pk>/', views.add_bill, name='add_bill'),
    path('register_admin/', views.register_admin, name='register_admin'),
    path('logout/', views.logout_view, name='logout'),
    path('add_unit/<int:pk>/', views.add_units, name='add_unit'),
    path('view_units/<int:pk>/', views.view_units, name='view_units'),
    path('payments_main/', views.payments_main, name='payments_main'),
    path('view_payments/<int:pk>/', views.view_payments, name='view_payments'),
    path('soa/<int:pk>/', views.soa, name='soa'),
    path('add_payment/<int:pk>/', views.add_payment, name='add_payment'),
    path('delete_payment/<int:pk>/', views.delete_payment, name='delete_payment'),
    path('delete_bill/<int:pk>/', views.delete_bill, name='delete_bill'),
    path('edit_bill/<int:pk>/', views.edit_bill, name='edit_bill'),
    path('payment_details/<int:pk>/', views.view_payment_details, name='payment_details'),
    path('view_proof_of_payment/<int:pk>/', views.view_proof_of_payment, name='view_proof_of_payment'),
    path('renew_lease/<int:pk>/', views.renew_lease, name='renew_lease'),
    path('edit_tenant/<int:pk>/', views.edit_tenant, name='edit_tenant'),
    path('edit_lease/<int:pk>/', views.edit_lease, name='edit_lease'),
    path('edit_payment/<int:pk>/', views.edit_payment, name='edit_payment')
]
